language: objective-c
osx_image: xcode9.2
xcode_sdk: iphonesimulator11.2
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace Cashmeter.xcworkspace -scheme Cashmeter CODE_SIGNING_REQUIRED=NO
